Albert - US10 : Marriage After 14
DQSevilla/cs555-gedcom pull request #16
Opened 2020-10-04 23:19 UTC by achen3680

2020-10-04 23:26 UTC, DQSevilla requested changes

2020-10-04 23:26 UTC, DQSevilla commented on project03.py
> +    if (person1['age'] > 14 and person2['age'] > 14):
This doesn't solve the user story, it must verify that **marriage** happens between of-age individuals. You are also not actually verifying the input gedcom file in main

2020-10-05 01:03 UTC, DQSevilla requested changes

2020-10-05 01:03 UTC, DQSevilla commented on project03.py
> +    if not family['divorced'] == 'NA':
No need for a divorce check

2020-10-05 01:03 UTC, DQSevilla commented on project03.py
> +        if (wife['age'] > 14 and husband['age'] > 14):
Not correct, must be 14 years after birth, not currently 14 years of age

2020-10-05 02:06 UTC, DQSevilla commented on project03.py
> +        if (wife['age'] > 14 and husband['age'] > 14):
To be clear, print out a helpful error message every time:
- A families marriage date minus the wife's birthday was less than 14 years (unix time)
- A familieis marriage date minus the husbamd's birthday was less than 14 years (unix time)

2020-10-05 20:12 UTC, Jarbo52 approved these changes
lgtm

2020-10-05 20:13 UTC, DQSevilla approved these changes
Fix conflicts and merge

2020-10-05 22:56 UTC, merged