fixed bugs so all unit tests passed
DQSevilla/cs555-gedcom pull request #27
Opened 2020-10-06 02:47 UTC by Jarbo52

2020-10-06 23:24 UTC, DQSevilla requested changes

2020-10-06 23:24 UTC, DQSevilla commented on examples.py
> +exampleDateEqualCurrentDate = '5 OCT 2020'
Use `datetime.now()` and `strftime` and a new `MONTHS` array (maybe we should make a utils file with a single months array at this point) to make the current date for `exampleDateEqualCurrentDate` and tomorrow's date for the `exampleDateAfterCurrentDate`

2020-10-08 21:41 UTC, ngoldstein51 approved these changes
Looks like small changes so master compiles, it should be fine. Thanks for all your hard work.

2020-10-08 21:49 UTC, DQSevilla approved these changes

2020-10-08 21:49 UTC, merged