male to female ratio
DQSevilla/cs555-gedcom pull request #43
Opened 2020-11-08 20:19 UTC by ngoldstein51

Finds the ration of males to females in the file

2020-11-09 04:25 UTC, DQSevilla approved these changes

2020-11-09 04:25 UTC, DQSevilla commented on verifier.py
> +            male_num += 1
Call this

2020-11-09 04:25 UTC, DQSevilla requested changes
fix

2020-11-09 04:26 UTC, DQSevilla commented on verifier.py
> +    return male_num/(male_num+female_num), female_num/(male_num+female_num)
Pfemale = 1 - Pmale, don't calculate it

2020-11-09 04:26 UTC, DQSevilla commented on verifier.py
> +    return male_num/(male_num+female_num), female_num/(male_num+female_num)
Also either return as a percent (* 100) or print as a percent when you actually call it

2020-11-09 19:43 UTC, ngoldstein51 commented on verifier.py
> +            male_num += 1
What does that mean?

2020-11-09 20:01 UTC, ngoldstein51 reviewed
Changes made

2020-11-09 20:01 UTC, ngoldstein51 commented on verifier.py
> +            male_num += 1
Oh, nevermind

2020-11-09 23:53 UTC, Jarbo52 approved these changes
lgtm

2020-11-10 00:34 UTC, DQSevilla approved these changes

2020-11-10 00:35 UTC, merged